version: '0.1'

services:
  nginx:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
